services:
  - type: worker
    name: weavebot-python
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: python bot.py
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: PLAYWRIGHT_HEADLESS
        value: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_ID
        sync: false
      - key: AIRTABLE_VIEW_ID
        sync: false
      - key: AIRTABLE_TABLE_NAME
        sync: false
      - key: AIRTABLE_UPDATES_TABLE_NAME
        sync: false
      - key: AIRTABLE_UPDATES_TABLE_ID
        sync: false
      - key: AIRTABLE_UPDATES_VIEW_ID
        sync: false 